'use strict';
const $=id=>document.getElementById(id),copy=x=>structuredClone(x);
let saved,rev,defaults,models=[],token='',dirty=false,history=[],selectedRecord=null,manualId=sessionStorage.getItem('consult-id'),parentId=null,lastManual=null,statusBusy=false;
const stateNames={ready:'已就绪',not_running:'未启动',wrong_model:'待切换模型',login_required:'需要登录',unknown:'页面加载中',model_unknown:'模型待确认',no_chatgpt_tab:'未打开聊天',multiple_tabs:'需指定标签页',draft_present:'有未发送草稿',busy:'正在回答',completed:'已完成',sent:'等待回答',dispatching:'发送待确认',preparing:'准备中',filled:'草稿待确认',abandoned:'已放弃',connection_error:'连接异常'};
function toast(s){$('toast').textContent=s;$('toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').hidden=true,4000)}
function error(e){$('notice').textContent=e.message||String(e);$('notice').hidden=false;toast(e.message||String(e))}
async function api(url,data){const r=await fetch(url,data===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json','X-Bridge-Token':token},body:JSON.stringify(data)});const v=await r.json();if(!r.ok)throw Error(v.error||'操作失败');return v}
async function action(button,fn){const t=button.textContent;button.disabled=true;button.textContent='处理中…';try{await fn()}catch(e){error(e)}finally{button.disabled=false;button.textContent=t}}
function changeView(){const view=['settings','compose','history'].includes(location.hash.slice(1))?location.hash.slice(1):'settings';document.querySelectorAll('[data-view]').forEach(e=>e.hidden=e.dataset.view!==view);document.querySelectorAll('[data-nav]').forEach(e=>e.classList.toggle('active',e.dataset.nav===view));$('view-label').textContent={settings:'偏好设置',compose:'手动咨询',history:'咨询记录'}[view];if(view==='history')loadHistory().catch(error);if(view==='compose'&&saved)$('compose-model').textContent=`${saved.model.label} · ${saved.enabled?'咨询已启用':'咨询已暂停'}`;}
function populateModels(current){const options=[...models];if(!options.some(m=>m.label===current.label))options.unshift(current);$('model').replaceChildren();for(const m of options){const e=document.createElement('option');e.value=JSON.stringify({label:m.label,family:m.family,effort:m.effort});e.textContent=m.label;$('model').append(e);if(m.label===current.label)e.selected=true}}
function fill(c){populateModels(c.model);$('enabled').checked=c.enabled;$('autoSelect').checked=c.model.autoSelect;document.querySelector(`[name=trigger][value=${c.trigger.mode}]`).checked=true;$('failedAttempts').value=c.trigger.failedAttempts;$('architecture').checked=c.trigger.architecture;$('conflictingEvidence').checked=c.trigger.conflictingEvidence;$('conversation-mode').value=c.conversation.mode;$('newTab').checked=c.conversation.openInNewTab;$('initial-prompt').value=c.prompt.text;$('prompt-placement').value=c.prompt.placement;$('max-sends').value=c.limits.maxSendsPerTask;$('wait-minutes').value=c.limits.waitMinutes;$('max-chars').value=c.limits.maxPromptChars;preview()}
function formConfig(){return {version:1,enabled:$('enabled').checked,model:{...JSON.parse($('model').value),autoSelect:$('autoSelect').checked},trigger:{mode:document.querySelector('[name=trigger]:checked').value,failedAttempts:Number($('failedAttempts').value),architecture:$('architecture').checked,conflictingEvidence:$('conflictingEvidence').checked},conversation:{mode:$('conversation-mode').value,openInNewTab:$('newTab').checked},limits:{maxSendsPerTask:Number($('max-sends').value),waitMinutes:Number($('wait-minutes').value),maxPromptChars:Number($('max-chars').value)},prompt:{placement:$('prompt-placement').value,text:$('initial-prompt').value}}}
function preview(){if(!$('model').value)return;const c=formConfig();dirty=JSON.stringify(c)!==JSON.stringify(saved);$('save-state').textContent=dirty?'有未保存的更改':'所有更改已保存';$('save').disabled=!dirty;$('undo').disabled=!dirty;$('preview-model').textContent=c.model.label;$('preview-enabled').textContent=c.enabled?'咨询已启用':'咨询已暂停';$('preview-trigger').textContent={smart:'智能判断',always:'每个新任务',manual:'仅手动'}[c.trigger.mode];$('preview-conversation').textContent={per_task:'按任务复用',always_new:'每次新建',reuse_recent:'跨任务复用'}[c.conversation.mode];$('preview-limit').textContent=`${c.limits.maxSendsPerTask||'—'} 条 / ${c.limits.waitMinutes||'—'} 分钟`;$('smart-options').hidden=c.trigger.mode!=='smart';$('prompt-count').textContent=`${c.prompt.text.length} / 12000`;$('wire-preview').textContent=`[咨询编号由工具自动附加]\n${c.prompt.text?c.prompt.text+'\n\n':''}[这里附加本次问题、代码与证据]`;$('conversation-help').textContent=c.conversation.mode==='reuse_recent'?'跨任务会共享上下文，适合持续讨论同一主题。明确追问始终沿用原聊天。':'明确发起的追问始终沿用原聊天。';$('trigger-help').textContent=c.trigger.mode==='always'?'每个新任务首次处理时咨询一次，不是每次工具调用都咨询。由 Codex 读取规则执行。':c.trigger.mode==='manual'?'你说“问一下网页顾问”，或在手动咨询页发送时才咨询。':'规则由 Codex 读取并执行，不会在后台自行发送消息。';$('preview-note').textContent=dirty?'当前为未保存预览，保存后生效。':'已保存。下一次咨询将使用这些设置。';}
async function refreshStatus(){if(statusBusy)return;statusBusy=true;try{const s=await api('/api/status');const p=s.pages.find(p=>p.id===s.selectedTabId);$('connection').className='connection '+(s.status==='ready'?'ok':'warn');$('connection').replaceChildren();const dot=document.createElement('i');$('connection').append(dot,document.createTextNode(stateNames[s.status]||s.status));$('browser-state').replaceChildren();const text=document.createElement('span');text.textContent=p?`网页：${p.modelLabels.join(' / ')||'待确认'} · ${p.login==='confirmed_by_ui'?'已登录':'登录待确认'}${s.active?' · 有进行中的咨询':''}`:stateNames[s.status]||s.status;$('browser-state').append(text);if(s.pages.length>1){const select=document.createElement('select');select.setAttribute('aria-label','指定咨询标签页');for(const p of s.pages){const o=document.createElement('option');o.value=p.id;o.textContent=`${p.modelLabels.join(' / ')} · ${p.url.split('/').at(-1)||'新聊天'}`;o.selected=p.id===s.selectedTabId;select.append(o)}select.onchange=()=>api('/api/browser/bind',{id:select.value}).then(()=>refreshStatus()).catch(error);$('browser-state').append(select)}if(s.status==='ready')$('notice').hidden=true;return s}catch(e){$('connection').className='connection warn';$('connection').textContent='连接异常';throw e}finally{statusBusy=false}}
async function loadHistory(){history=await api('/api/history');$('history-count').textContent=history.filter(r=>!r.archived).length;renderHistory()}
function date(s){return new Intl.DateTimeFormat('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s))}
function renderHistory(){const query=$('search').value.toLowerCase(),filter=$('history-filter').value,rows=history.filter(r=>(filter==='archived'?r.archived:!r.archived)&&(filter==='completed'?r.status==='completed':filter==='pending'?!['completed','abandoned'].includes(r.status):true)&&`${r.title} ${r.taskName||r.task} ${r.task} ${r.id}`.toLowerCase().includes(query));$('history-list').replaceChildren();for(const r of rows){const row=document.createElement('div');row.className='history-row';row.dataset.id=r.id;row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label','查看 '+r.title);const icon=document.createElement('span');icon.className='record-icon';icon.textContent='◷';const info=document.createElement('div');info.className='record-content';const title=document.createElement('div');title.className='record-title';title.textContent=r.title;const meta=document.createElement('div');meta.className='record-meta';meta.textContent=`${date(r.createdAt)}  ·  ${r.model||'未发送'}  ·  ${r.taskName||r.task}`;info.append(title,meta);const state=document.createElement('span');state.className='status-pill '+r.status;state.textContent=stateNames[r.status]||r.status;row.append(icon,info,state);row.onclick=()=>openDetail(r.id).catch(error);row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();row.click()}};$('history-list').append(row)}if(!rows.length){const e=document.createElement('div');e.className='history-empty';e.textContent=query?'没有匹配的咨询记录':'这里还没有记录';$('history-list').append(e)}}
async function openDetail(id){const r=await api('/api/requests/'+encodeURIComponent(id));selectedRecord=r;$('detail-meta').textContent=`${stateNames[r.status]||r.status} · ${date(r.createdAt)} · ${r.id}`;$('detail-question').textContent=r.prompt;$('detail-answer').textContent=r.answer||r.lastError||'尚未取得完整回答';$('detail-assessment').textContent=r.assessment||'尚未记录采纳与验证结果';$('detail-config').textContent=r.configSnapshot?JSON.stringify(r.configSnapshot,null,2):'旧版记录未保存配置快照';$('detail-chat').hidden=!r.url;if(r.url)$('detail-chat').href=r.url;$('download-md').href=`/api/requests/${id}/export?format=md`;$('download-json').href=`/api/requests/${id}/export?format=json`;$('detail-followup').hidden=r.status!=='completed';$('detail-release').hidden=['completed','abandoned'].includes(r.status);$('detail-archive').textContent=history.find(x=>x.id===id)?.archived?'取消归档':'归档';$('detail').showModal()}
function newQuestion(parent=null){parentId=parent?.id||null;manualId=null;lastManual=null;sessionStorage.removeItem('consult-id');$('question').value='';$('task').value=parent?.taskName||parent?.task||'';$('task').disabled=!!parent;$('compose-title').textContent=parent?'继续追问':'新咨询';$('compose-parent').textContent=parent?'将沿用记录 '+parent.id+' 的聊天。':'';$('send-question').textContent='发送咨询 ↗';$('answer').hidden=true;$('answer-empty').hidden=false;$('answer-link').hidden=true;$('poll').hidden=true;$('followup').hidden=true;$('answer-status').textContent='发送后在这里查看进度';}
function showAnswer(r){lastManual=r;$('answer-status').textContent=r.waitBudgetExceeded?'已超过等待预算，记录已保留，可稍后查询':(r.observation?({sent_confirmation_pending:'已点击发送，正在确认结果',send_outcome_unknown:'发送结果待确认，请查询原记录',message_not_visible_do_not_resend:'消息暂不可见，请检查原聊天，勿重复发送'}[r.observation]||'等待网页完成加载与确认'):stateNames[r.status]||r.status);$('answer-empty').hidden=!!r.answer;$('answer').hidden=!r.answer;$('answer').textContent=r.answer||'';$('answer-link').hidden=!r.url;if(r.url)$('answer-link').href=r.url;$('poll').hidden=['completed','abandoned'].includes(r.status)&&!r.observation;$('followup').hidden=r.status!=='completed';if(r.status==='completed')$('send-question').textContent='已发送 · 点击新建继续';}
async function poll(){if(!manualId)return;const r=await api('/api/poll',{id:manualId});showAnswer(r);loadHistory().catch(()=>{});return r}
window.addEventListener('hashchange',changeView);window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
$('settings-form').addEventListener('input',preview);$('settings-form').addEventListener('change',preview);$('settings-form').onsubmit=e=>{e.preventDefault();action($('save'),async()=>{const result=await api('/api/config',{config:formConfig(),revision:rev});saved=result.config;rev=result.revision;preview();toast('设置已保存，下次咨询生效');await refreshStatus()}).then(preview)};
$('undo').onclick=()=>fill(saved);$('reset').onclick=()=>{fill(copy(defaults));toast('已载入默认设置，保存后生效')};$('export-config').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(formConfig(),null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='chatgpt-bridge-config.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
$('import-config').onchange=async e=>{try{const c=JSON.parse(await e.target.files[0].text());const valid=await api('/api/config/validate',{config:c});fill(valid.config);toast('配置已导入表单，保存后生效')}catch(e){error(e)}finally{e.target.value=''}};
$('refresh').onclick=()=>action($('refresh'),refreshStatus);$('start').onclick=()=>action($('start'),async()=>{const s=await api('/api/browser/start',{});if(s.notice)toast(s.notice);await refreshStatus()});
$('scan-models').onclick=()=>action($('scan-models'),async()=>{const current=formConfig().model;const r=await api('/api/models/scan',{});models=r.models;populateModels(current);preview();$('models-note').textContent=`已读取 ${models.length} 个高推理模型${r.unavailable.length?'，部分选项不可用':''}`;toast('模型列表已更新，网页已恢复原选择');await refreshStatus()});
$('apply-model').onclick=()=>action($('apply-model'),async()=>{if(dirty)throw Error('请先保存设置，再应用到网页');await api('/api/models/apply',{});toast('已应用到 ChatGPT 网页');await refreshStatus()});
$('compose-form').onsubmit=e=>{e.preventDefault();action($('send-question'),async()=>{if(lastManual?.status==='completed')throw Error('这条咨询已完成，请点击新建或继续追问');manualId ||= `web-${Date.now()}-${crypto.randomUUID().slice(0,6)}`;sessionStorage.setItem('consult-id',manualId);const task=$('task').value.trim();const r=await api('/api/consult',{id:manualId,task,parent:parentId,prompt:$('question').value});showAnswer(r);toast(r.reused?'已找到原请求，没有重复发送':'已发送，可以继续其他工作');await loadHistory();await refreshStatus()})};
$('new-question').onclick=()=>newQuestion();$('poll').onclick=()=>action($('poll'),poll);$('followup').onclick=()=>newQuestion(lastManual);$('search').oninput=renderHistory;$('history-filter').onchange=renderHistory;$('refresh-history').onclick=()=>action($('refresh-history'),loadHistory);
$('close-detail').onclick=()=>$('detail').close();$('detail-followup').onclick=()=>{const r=selectedRecord;$('detail').close();newQuestion(r);location.hash='compose'};
$('detail-archive').onclick=()=>action($('detail-archive'),async()=>{await api('/api/archive',{id:selectedRecord.id,archived:!history.find(x=>x.id===selectedRecord.id)?.archived});$('detail').close();await loadHistory();toast('记录列表已更新，网页聊天未删除')});
$('detail-release').onclick=()=>action($('detail-release'),async()=>{if(!confirm('放弃本地跟踪？这不会停止 ChatGPT 正在处理的请求，也不会清空草稿。'))return;await api('/api/release',{id:selectedRecord.id});$('detail').close();await loadHistory();await refreshStatus()});
$('help').onclick=()=>$('help-dialog').showModal();$('close-help').onclick=()=>$('help-dialog').close();
async function init(){const b=await api('/api/bootstrap');saved=b.config;rev=b.revision;defaults=b.defaults;models=b.models.models;token=b.token;$('config-path').textContent=b.configPath;fill(saved);changeView();await loadHistory();await refreshStatus();if(manualId){try{showAnswer(await api('/api/requests/'+manualId))}catch{manualId=null;sessionStorage.removeItem('consult-id')}}
 if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_consultation_settings',description:'Read the saved consultation settings and current unsaved-change state.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async input=>{if(!input||Object.keys(input).length)throw Error('No arguments expected');return {config:saved,unsavedChanges:dirty}}})}catch{}}
}
init().catch(error);setInterval(()=>{if(!document.hidden){refreshStatus().catch(()=>{});if(manualId&&lastManual&&!lastManual.waitBudgetExceeded&&!['completed','abandoned'].includes(lastManual.status))poll().catch(()=>{})}},10000);
